#!/bin/sh

# Monitor settings
if ! pgrep -x sxhkd > /dev/null; then
    sxhkd &
fi
bspc monitor eDP-1 -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width 5
bspc config window_gap 2
./.fehbg

xsetroot -cursor_name left_ptr &

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#ffffff"

setxkbmap -model pc104 -layout us_intl &
polybar &
